dateModified: 1677864342
email:
  fromEmail: derrick@dgrigg.com
  fromName: Boilerplate
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3a51c4ef-5f59-44d3-9d0c-642518f9c080: Boilerplate # Boilerplate
    03c6a97d-758f-44f9-b773-f1b6a8df9590: Common # Common
    f0d68455-b7b8-440b-9030-9cebe3251626: Boilerplate # Boilerplate
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: F1DIYS679I7O3D60MSJFH92I
    schemaVersion: 4.2.0
    settings:
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
      refreshMode: 3
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: build
      publicPath: web
  mix-manifest:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: RXFOW3DM28EBVRZFR0FUBJRD
    schemaVersion: 2.0.4
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: U10ZHS8NJ5EBR4VO9R530LTR
    schemaVersion: 3.0.11
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: Boilerplate
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
